apps/posts/urls.py
# urls.py
from django.conf.urls import patterns, url
from apps.posts.views import PostCreate, PostUpdate, PostDelete, PostList, PostDetail

urlpatterns = patterns('',
                       # ...
                       url(r'post/add/$', PostCreate.as_view(), name='post_add'),
                       url(r'post/(?P<pk>\d+)/$',
                           PostDetail.as_view(), name='post_view'),
                       url(r'post/(?P<pk>\d+)/update/$',
                           PostUpdate.as_view(), name='post_update'),
                       url(r'post/(?P<pk>\d+)/delete/$',
                           PostDelete.as_view(), name='post_delete'),
                       url(r'post/list/$', PostList.as_view()),
                       )

tecp2p/urls.py
from django.conf.urls import patterns, include, url
import settings
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
                       # Examples:
                       # url(r'^$', 'tecp2p.views.home', name='home'),
                       # url(r'^blog/', include('blog.urls')),
                       url(r'^', include(
                           'apps.posts.urls', namespace="posts")),
                       url(r'^admin/', include(admin.site.urls)),
                       )

if settings.DEBUG:
    urlpatterns += patterns('',
                           (r'^media/(?P<path>.*)$', 'django.views.static.serve',
                            {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
                            )

apps/posts/models.py
from django.db import models
from easy_thumbnails.fields import ThumbnailerImageField


class Post(models.Model):

    title = models.CharField(max_length=60)
    body = models.TextField()
    # image = models.ImageField(upload_to = 'uploads/images/', blank=True, null=True)
    photo = ThumbnailerImageField(
        upload_to='uploads/images/', blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return self.title

apps/posts/forms.py
# from django import forms 
# from .models import Post 

# class PostEditForm(forms.ModelForm):
#     class Meta:
#         model = Post
#         fields = ('title', 'body', 'created')
    

apps/posts/views.py
# views.py
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from django.core.urlresolvers import reverse_lazy
from apps.posts.models import Post
# import the logging library
import logging
# from django.shortcuts import render, redirect

# Get an instance of a logger
logger = logging.getLogger(__name__)


class PostCreate(CreateView):
    model = Post
    fields = ['title', 'body', 'photo']
    success_url = '/post/add/'


class PostUpdate(UpdateView):
    model = Post
    fields = ['title', 'body']


class PostDelete(DeleteView):
    model = Post
    # success_url = reverse_lazy('post-list')


class PostList(ListView):
    queryset = Post.objects.all().order_by('-created')
    # model = Post


class PostDetail(DetailView):
    model = Post

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(PostDetail, self).get_context_data(**kwargs)
        # Add in a QuerySet of all the books
        context['post_list'] = Post.objects.all()
        return context

tecp2p/views.py
from django.http import Http404
from django.shortcuts import render_to_response
from django.http import HttpResponse

def my_custom_404_view(request):
    html = "<html><body>Url = %s.</body></html>" % request_path
    return HttpResponse(html)

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block title %}
            TecP2p´s blog
        {% endblock title %}</title>

    <!-- Bootstrap core CSS -->
    <link href="{{STATIC_URL}}bootstrap/css/bootstrap.css" rel="stylesheet">

    <!-- Add custom CSS here -->
    <link href="{{STATIC_URL}}bootstrap/css/blog-home.css" rel="stylesheet">
    {% block links %}{% endblock %}

</head>
  <body>
    {% block content %}{% endblock %}

    <!-- JavaScript -->
    <script src="{{STATIC_URL}}bootstrap/js/jquery-1.10.2.js"></script>
    <script src="{{STATIC_URL}}bootstrap/js/bootstrap.js"></script>
    {% block scripts %}{% endblock %}
  </body>
</html>

templates/posts/post_detail.html
{% extends 'base.html' %}

{% block links %}
    <link href="css/blog-post.css" rel="stylesheet">
{% endblock %}

{% block content %}
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="index.php">Start Bootstrap</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav">
                    <li><a href="#about">About</a>
                    </li>
                    <li><a href="#services">Services</a>
                    </li>
                    <li><a href="#contact">Contact</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <div class="container">

        <div class="row">
            <div class="col-lg-8">

                <!-- the actual blog post: title/author/date/content -->
                <h1>{{ post.title }}</h1>
                <p class="lead">by <a href="index.php">Start Bootstrap</a>
                </p>
                <hr>
                <p>
                    <span class="glyphicon glyphicon-time"></span> Posted on August 24, 2013 at 9:00 PM</p>
                <hr>
                {% if post.photo %}
                    <img style="max-width: 100%" src="{{ post.photo.post_detail.url }}" alt="" />
                {% endif %}
                <hr>
                <p class="lead">Science cuts two ways, of course; its products can be used for both good and evil. But there's no turning back from science. The early warnings about technological dangers also come from science.</p>
                <p>{{ post.body }}</p>
                <p><strong>Placeholder text by:</strong>
                </p>
                <ul>
                    <li><a href="http://spaceipsum.com/">Space Ipsum</a>
                    </li>
                    <li><a href="http://cupcakeipsum.com/">Cupcake Ipsum</a>
                    </li>
                    <li><a href="http://tunaipsum.com/">Tuna Ipsum</a>
                    </li>
                </ul>

                <hr>

                <!-- the comment box -->
                <div class="well">
                    <h4>Leave a Comment:</h4>
                    <form role="form">
                        <div class="form-group">
                            <textarea class="form-control" rows="3"></textarea>
                        </div>
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </form>
                </div>

                <hr>

                <!-- the comments -->
                <h3>Start Bootstrap
                    <small>9:41 PM on August 24, 2013</small>
                </h3>
                <p>This has to be the worst blog post I have ever read. It simply makes no sense. You start off by talking about space or something, then you randomly start babbling about cupcakes, and you end off with random fish names.</p>

                <h3>Start Bootstrap
                    <small>9:47 PM on August 24, 2013</small>
                </h3>
                <p>Don't listen to this guy, any blog with the categories 'dinosaurs, spaceships, fried foods, wild animals, alien abductions, business casual, robots, and fireworks' has true potential.</p>

            </div>

            <div class="col-lg-4">
                <div class="well">
                    <h4>Blog Search</h4>
                    <div class="input-group">
                        <input type="text" class="form-control">
                        <span class="input-group-btn">
                            <button class="btn btn-default" type="button">
                                <span class="glyphicon glyphicon-search"></span>
                            </button>
                        </span>
                    </div>
                    <!-- /input-group -->
                </div>
                <!-- /well -->
                <div class="well">
                    <h4>Popular Blog Categories</h4>
                    <div class="row">
                        <div class="col-lg-6">
                            <ul class="list-unstyled">
                                <li><a href="#dinosaurs">Dinosaurs</a>
                                </li>
                                <li><a href="#spaceships">Spaceships</a>
                                </li>
                                <li><a href="#fried-foods">Fried Foods</a>
                                </li>
                                <li><a href="#wild-animals">Wild Animals</a>
                                </li>
                            </ul>
                        </div>
                        <div class="col-lg-6">
                            <ul class="list-unstyled">
                                <li><a href="#alien-abductions">Alien Abductions</a>
                                </li>
                                <li><a href="#business-casual">Business Casual</a>
                                </li>
                                <li><a href="#robots">Robots</a>
                                </li>
                                <li><a href="#fireworks">Fireworks</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
                <!-- /well -->
                <div class="well">
                    <h4>Side Widget Well</h4>
                    <p>Bootstrap's default wells work great for side widgets! What is a widget anyways...?</p>
                </div>
                <!-- /well -->
            </div>
        </div>

        <hr>

        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; Company 2013</p>
                </div>
            </div>
        </footer>

    </div>
{% endblock %}

templates/posts/post_form.html
{% extends 'base.html' %}
{% load bootstrap %}

{% block content %}
	<form enctype="multipart/form-data" action="" method="post" role="form">{% csrf_token %}
	{{ form|bootstrap }}
	<input type="submit" class="btn btn-primary" value="Submit" />
	</form>
{% endblock %}

templates/posts/post_list.html
{% extends 'base.html' %}
{% load thumbnail %}

{% block content %}
    
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="index.php">Start Bootstrap</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav">
                    <li><a href="#about">About</a>
                    </li>
                    <li><a href="#services">Services</a>
                    </li>
                    <li><a href="#contact">Contact</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <div class="container">

        <div class="row">
            <div class="col-lg-8">

                <!-- blog entry -->
                {% for post in post_list %}
                    <h1><a href="{% url 'posts:post_view' post.id %}">{{ post.title }}</a>
                    </h1>
                    <p class="lead">by <a href="index.php">Start Bootstrap</a>
                    </p>
                    <hr>
                    <p>
                        <span class="glyphicon glyphicon-time"></span> Posted on August 28, 2013 at 10:00 PM</p>
                    <hr>
                    {% if post.photo %}
                    <img style="max-width: 100%" src="{{ post.photo.post.url }}" alt="" />
                    {% endif %}
                    <hr>
                    <p>{{ post.body }}</p>
                    <a class="btn btn-primary" href="#">Read More <span class="glyphicon glyphicon-chevron-right"></span></a>

                    <hr>
                {% endfor %}

                <!-- pager -->
                <ul class="pager">
                    <li class="previous"><a href="#">&larr; Older</a>
                    </li>
                    <li class="next"><a href="#">Newer &rarr;</a>
                    </li>
                </ul>

            </div>

            <div class="col-lg-4">
                <div class="well">
                    <h4>Blog Search</h4>
                    <div class="input-group">
                        <input type="text" class="form-control">
                        <span class="input-group-btn">
                            <button class="btn btn-default" type="button">
                                <span class="glyphicon glyphicon-search"></span>
                            </button>
                        </span>
                    </div>
                    <!-- /input-group -->
                </div>
                <!-- /well -->
                <div class="well">
                    <h4>Popular Blog Categories</h4>
                    <div class="row">
                        <div class="col-lg-6">
                            <ul class="list-unstyled">
                                <li><a href="#dinosaurs">Dinosaurs</a>
                                </li>
                                <li><a href="#spaceships">Spaceships</a>
                                </li>
                                <li><a href="#fried-foods">Fried Foods</a>
                                </li>
                                <li><a href="#wild-animals">Wild Animals</a>
                                </li>
                            </ul>
                        </div>
                        <div class="col-lg-6">
                            <ul class="list-unstyled">
                                <li><a href="#alien-abductions">Alien Abductions</a>
                                </li>
                                <li><a href="#business-casual">Business Casual</a>
                                </li>
                                <li><a href="#robots">Robots</a>
                                </li>
                                <li><a href="#fireworks">Fireworks</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
                <!-- /well -->
                <div class="well">
                    <h4>Side Widget Well</h4>
                    <p>Bootstrap's default wells work great for side widgets! What is a widget anyways...?</p>
                </div>
                <!-- /well -->
            </div>
        </div>

        <hr>

        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; Company 2013</p>
                </div>
            </div>
        </footer>

    </div>
    <!-- /.container -->

{% endblock %}